Initial commit of active learning code
ai2es/ptype-physical pull request #14
Opened 2022-11-23 22:54 UTC by jsschreck

2022-12-09 20:36 UTC, djgagne requested changes
I caught a few small things to adjust before committing.

2022-12-09 20:36 UTC, djgagne commented on applications/active_training.py
> +    parent = "/glade/work/schreck/repos/ptype-physical/applications/"
Can you make the path relative, configurable, or us os.getcwd() so the code is not user specific?

2022-12-09 20:36 UTC, djgagne commented on applications/active_training.py
> +        #PBS -l select=1:ncpus=8:ngpus=1:mem=128GB
Can you make the PBS arguments configurable instead of hard coded?

2022-12-09 20:36 UTC, djgagne commented on applications/active_training.py
> +            scaled_data, scalers = preprocess_data(
Can you save the scalers to the save_loc space?

2022-12-09 20:36 UTC, djgagne commented on ptype/plotting.py
> +        path = f"/glade/u/home/jwillson/winter-ptype/images/{model_name}/"
Remove hard-coded path and specify path in filename.

2022-12-12 15:41 UTC, jsschreck commented on applications/active_training.py
> +    parent = "/glade/work/schreck/repos/ptype-physical/applications/"
Fixed!

2022-12-12 15:42 UTC, jsschreck commented on applications/active_training.py
> +        #PBS -l select=1:ncpus=8:ngpus=1:mem=128GB
I could make them parser options. I've been increasingly doing this in other projects (automatically create the launch script and submit it); do you think I should potentially move these options to the config file, or a totally separate config file?

2022-12-12 15:42 UTC, jsschreck commented on applications/active_training.py
> +            scaled_data, scalers = preprocess_data(
I have updated the pull request to utilize your new bridgescaler.

2022-12-21 14:56 UTC, merged